### ISSUE TITLE
Einthusan addon does not seem to log your user name and password required to unlock the UHD streams.

### ISSUE THREAD

**Issue by DTonline** [reasonsrepo/repository.reasonsrepo#4]
Einthusan addon does not seem to log your user name and password required to unlock the UHD streams. Only the HD/SD streams seem to work. Tried the addon on Kodi 18.  Appreciate if you could fix this issue. Thank you.

**Comment by reasonsrepo** [comment]
Fixed

**Comment by DTonline** [comment]
Thanks for trying, but the issue seems to still exist. Tried it today and gives me the same error. Let me know if you need the log file. 
    On Tuesday, February 12, 2019, 1:32:33 PM EST, Reasons Repo <notifications@github.com> wrote:  
 
 
Fixed
